version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: book-recs-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-book_recommendations}
      POSTGRES_USER: ${DB_USER:-terezasaskova}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../ingestion/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./init-airflow-db.sql:/docker-entrypoint-initdb.d/02-airflow.sql
    ports:
      - "5060:5432"
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-terezasaskova}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
  airflow_network:
    external: true