version: '3.8'

services:
#Database - nothing built locally => postgres 13 from prebuilt docker hub image .... 
  postgres:
    image: postgres:13
    container_name: book-recs-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env.development
    ports: #HOST_PORT(laptop port):CONTAINER_PORT(inside container)
      - "${DB_PORT}:5432"  

    volumes: 
      #volume name : container path = docker-compose down → Data safe in volume 
      - postgres-data:/var/lib/postgresql/data
      #local path : container path
        #   1. Container starts for first time
        #   2. Postgres sees schema.sql
        #   3. Runs: psql -U $POSTGRES_USER -d $POSTGRES_DB < schema.sql
        #   4.  tables are created
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    healthcheck:
      # if postgres is ready
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks: #all container in same network are now connected... = hostname = service name
      - book-recs-network
    restart: unless-stopped

networks:
  book-recs-network:
    driver: bridge
    name: book-recs-network

volumes:
  postgres-data:
    name: book-recs-postgres-data
