version: '3.8'

services:
  airflow-webserver:
    build:
      context: ../..
      dockerfile: docker/airflow/Dockerfile
    container_name: airflow_webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@host.docker.internal:5432/mydb
    ports:
      - "8081:8080"
    volumes:
      - ../../src/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
    networks:
      - airflow_network

volumes:
  airflow_logs:

networks:
  airflow_network:
    driver: bridge