DROP TABLE IF EXISTS recommendations_cache CASCADE;
DROP TABLE IF EXISTS book_similarities CASCADE;
DROP TABLE IF EXISTS item_factors CASCADE;
DROP TABLE IF EXISTS user_factors CASCADE;
DROP TABLE IF EXISTS book_features CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS books CASCADE;

-- SOURCE TABLES 
-- ============================================================

-- Books table (enriched with Google Books data)
CREATE TABLE books (
    isbn VARCHAR(13) PRIMARY KEY, --important
    
    -- Kaggle original data (for reference)
    kaggle_title VARCHAR(500),
    kaggle_author VARCHAR(255),
    kaggle_year INT,
    kaggle_publisher VARCHAR(255),
    
    -- Google Books enriched data (what we actually use)
    title VARCHAR(500) NOT NULL,
    description TEXT,  -- MOST IMPORTANT for ML
    authors TEXT[],    -- Array of authors
    categories TEXT[], -- Array of genres/categories
    publisher VARCHAR(255),
    published_date VARCHAR(50),  -- Can be year or full date
    page_count INT,
    language VARCHAR(10),
    enriched BOOLEAN DEFAULT FALSE,
    data_source VARCHAR(20),  -- 'google_books' or 'kaggle_only'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for fast lookups
CREATE INDEX idx_books_title ON books(title);
CREATE INDEX idx_books_authors ON books USING GIN(authors);
CREATE INDEX idx_books_categories ON books USING GIN(categories);
CREATE INDEX idx_books_language ON books(language);

-- Users table
CREATE TABLE users (
    user_id INTEGER PRIMARY KEY,
    location VARCHAR(255),
    age INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Ratings table
CREATE TABLE ratings (
    rating_id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    isbn VARCHAR(13) REFERENCES books(isbn) ON DELETE CASCADE,
    rating INTEGER CHECK (rating >= 0 AND rating <= 10),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, isbn)  -- One rating per user-book pair
);

-- Indexes for fast queries
CREATE INDEX idx_ratings_user ON ratings(user_id);
CREATE INDEX idx_ratings_book ON ratings(isbn);
CREATE INDEX idx_ratings_rating ON ratings(rating);
CREATE INDEX idx_ratings_timestamp ON ratings(timestamp);


-- PRE-COMPUTED TABLES (Generated by Spark)
-- ============================================================

-- Book features (TF-IDF vectors, normalized metadata)
CREATE TABLE book_features (
    isbn VARCHAR(13) PRIMARY KEY REFERENCES books(isbn),
    tfidf_vector FLOAT8[],      -- TF-IDF from description
    category_vector FLOAT8[],   -- One-hot encoded categories
    page_count_norm FLOAT8,     -- Normalized page count
    year_norm FLOAT8,           -- Normalized year
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User factors from ALS (collaborative filtering)
CREATE TABLE user_factors (
    user_id INTEGER PRIMARY KEY REFERENCES users(user_id),
    factors FLOAT8[],  -- Latent factors (e.g., 50-dim vector)
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Item factors from ALS (collaborative filtering)
CREATE TABLE item_factors (
    isbn VARCHAR(13) PRIMARY KEY REFERENCES books(isbn),
    factors FLOAT8[],  -- Latent factors (e.g., 50-dim vector)
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Book-to-book similarities (content-based)
CREATE TABLE book_similarities (
    isbn_a VARCHAR(13) REFERENCES books(isbn) ON DELETE CASCADE,
    isbn_b VARCHAR(13) REFERENCES books(isbn) ON DELETE CASCADE,
    similarity_score FLOAT8,
    PRIMARY KEY (isbn_a, isbn_b),
    CHECK (isbn_a < isbn_b)  -- Store each pair only once
);

CREATE INDEX idx_book_sim_a ON book_similarities(isbn_a, similarity_score DESC);
CREATE INDEX idx_book_sim_b ON book_similarities(isbn_b, similarity_score DESC);

-- Cached recommendations (hybrid scores)
CREATE TABLE recommendations_cache (
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
    isbn VARCHAR(13) REFERENCES books(isbn) ON DELETE CASCADE,
    score FLOAT8,  -- Hybrid score (collaborative + content)
    rank INTEGER,  -- 1 = top recommendation
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, isbn)
);

CREATE INDEX idx_rec_user_rank ON recommendations_cache(user_id, rank);
CREATE INDEX idx_rec_score ON recommendations_cache(score DESC);